user:
  firstname:
    max_length: 25
  lastname:
    max_length: 50
  address:
    max_length: 255
  city:
    max_length: 50
  country:
    max_length: 50
  phone:
    min_length: 10
    max_length: 12
  company:
    max_length: 100
  password:
    max_length: 16
    min_length: 8
  state:
    max_length: 50

suggest_product:
  product_name:
    max_length: 50

product_group:
  group_name:
    max_length: 50
  content:
    max_length: 255

product:
  product_name:
    max_length: 50
  description:
    max_length: 255
  per_page:
    size: 10

comment:
  content:
    max_length: 255
