auth:
  admin:
    role: 1

user:
  firstname:
    max_length: 25
  lastname:
    max_length: 50
  address:
    max_length: 255
  city:
    max_length: 50
  country:
    max_length: 50
  phone:
    min_length: 10
    max_length: 12
  company:
    max_length: 100
  password:
    max_length: 16
    min_length: 8
  state:
    max_length: 50

suggest_product:
  product_name:
    max_length: 50

product_group:
  group_name:
    max_length: 50
  content:
    max_length: 255

product:
  product_name:
    max_length: 50
  description:
    max_length: 255
  per_page:
    size: 10
  rating:
    zero: 0
    round: 1
  name:
    empty: ""

order:
  per_page:
    size: 10
  total_price:
    round: 2

comment:
  content:
    max_length: 255

cart:
  product:
    quantity: 1
  discount:
    percent: 100
  number_order:
    min: 0
    increase: 1
  per_page:
    size: 5
  total_price:
    no_price: 0
  item:
    than_one: 1

quantity:
  number_field:
    min: 1
  increase:
    number: 1
  product:
    not_available: 0

order:
  status:
    considered: 1
    moving: 2
    arrived: 3
  per_page:
    size: 10

admin:
  email:
    default: "trungngo1996dn@gmail.com"
    wait: 5
